services:
  # App NestJS
  app:
    build: .
    container_name: assetflux-app
    ports:
      - "3000:3000"
    env_file: .env
    environment: 
      - REDIS_HOST=redis
      - DATABASE_URL=http://dynamodb-local:8000
      - S3_ENDPOINT=http://localstack-s3:4566
    depends_on:
      - dynamodb-local
      - localstack
      - redis
    networks:
      - assetflux-network

  # DynamoDB Local
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - assetflux-network

  # LocalStack "S3 Local"
  localstack:
    image: localstack/localstack
    container_name: localstack-s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./docker/localstack:/var/lib/localstack"
    networks:
      - assetflux-network
    
  # Cache Layer
  redis:
    image: redis:alpine
    container_name: assetflux-cache
    ports:
      - "6379:6379"
    networks:
      - assetflux-network

networks:
  assetflux-network:
    driver: bridge